
BASE_URL: https://www.saucedemo.com/
INVENTORY_URL: https://www.saucedemo.com/inventory.html
CART_URL: https://www.saucedemo.com/cart.html
CHECKOUT_ONE_URL: https://www.saucedemo.com/checkout-step-one.html
CHECKOUT_TWO_URL: https://www.saucedemo.com/checkout-step-two.html
CHECKOUT_COMPLETE_URL: https://www.saucedemo.com/checkout-complete.html

login: standard_user
password: secret_sauce